### ISSUE TITLE
How to use other quotation marks? (#9 but you closed it)

### ISSUE THREAD

**Issue by louisabraham** [BinetReseau/polytechnique-LaTeX#10]
Can you provide your latex source files for your files of #9 please?

Maybe I did something wrong.

http://termbin.com/6koi
gives [test-quotation-normal.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1799396/test-quotation-normal.pdf)

http://termbin.com/ohnm
gives [test-quotation.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1799397/test-quotation.pdf)

(I used this markdown file to generate those two files:

    ---
    header-includes:
    - '\usepackage[german=quotes]{csquotes}'
    lang: de
    ---

    "Hallo"
)

**Comment by w2ak** [comment]
You're right I gave the logs but not the sources. Weird. Here are the sources and outputs.

[english.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831339/english.pdf)
[english.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831340/english.tex.txt)
[english_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831341/english_x.pdf)
[english_x.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831342/english_x.tex.txt)
[french.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831343/french.pdf)
[french.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831344/french.tex.txt)
[french_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831345/french_x.pdf)
[french_x.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831346/french_x.tex.txt)
[german.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831347/german.pdf)
[german.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831348/german.tex.txt)
[german_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831349/german_x.pdf)
[german_x.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831350/german_x.tex.txt)

Little advice, when having problems with pandoc, start by trying only latex and reducing your tex file to a minimal example. That said, it might just be the fact that you don't use the `\textquote` command as (I think, old memory) advised in the csquotes package.

**Comment by w2ak** [comment]
By the way. You can still comment on closed issues. The point is that admins can then reopen them. Creating a new one works when there are only four issues on a small project but it is still a pain for organization.

![selection_050](https://user-images.githubusercontent.com/12606137/37684850-a6aa0eb2-2c91-11e8-8bca-b50581e02ebe.png)

**Comment by w2ak** [comment]
Duplicate. Use #9.
