### ISSUE TITLE
Where is the makefile_unix ?

### ISSUE THREAD

**Issue by JocelynBe** [BinetReseau/polytechnique-LaTeX#11]
It's not in the zip, that's a problem.

**Comment by w2ak** [comment]
While the pdf guide is indeed outdated and mentions a `makefile_unix.sh` file that doesn't exist anymore, the file named `README` is.

Use `Makefile`.

**Comment by w2ak** [comment]
fb74fa50a6d303cb58de46d09cbf4e3800442983

Just deprecated the automatic installation instructions as a temporary fix.
