### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by fishilico** [BinetReseau/polytechnique-LaTeX#2]
When trying to compile `source/polytechnique.dtx` I get:

```
! Package pdftex.def Error: File `logovert.pdf' not found.
```

It seems this project requires some files (`filetlongrouge.pdf`, `filetcourtbleuclair.pdf`, `filetcourtbleu.pdf`, `logovert.pdf`, `logohori.pdf` and `armes.pdf`) which are not provided by this project. Where could I get these missing files?

Cheers!

**Comment by denismerigoux** [comment]
These files contains the logos and graphic elements of the school, which have been provided by the DIRCOM. I don't wanted to pout them online for everyone to access but they are provided with the distributed version of the package accessible only for students (at typographix.binets.fr on the plâtal and soon on the intranet for the others).

**Comment by Feandil** [comment]
You mean these ones: https://github.com/BinetReseau/infobar ?

**Comment by denismerigoux** [comment]
En effet. C'est ce qu'on appelle un fruitage.
