### ISSUE TITLE
How to use other quotation marks?

### ISSUE THREAD

**Issue by louisabraham** [BinetReseau/polytechnique-LaTeX#9]
I would like to type a document in german, and use the appropriate quotation marks („Guten Tag!“).
Similarly, one may want to type normal quotation marks ("Salut") and render french quotation marks (« omelette du fromage »).

I tried things like:

    \usepackage[german=quotes]{csquotes}

but it didn't work… (It does work when not using the polytechnique package)

**Comment by w2ak** [comment]
Please provide a minimal example where it works without the `polytechnique` package and doesn't work with it.

**Comment by w2ak** [comment]
[english.log](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788432/english.log)
[english.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788433/english.pdf)
[english_x.log](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788434/english_x.log)
[english_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788435/english_x.pdf)
[french.log](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788436/french.log)
[french.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788437/french.pdf)
[french_x.log](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788438/french_x.log)
[french_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788439/french_x.pdf)
[german.log](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788440/german.log)
[german.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788441/german.pdf)
[german_x.log](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788442/german_x.log)
[german_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1788443/german_x.pdf)

**Comment by w2ak** [comment]
You're right I gave the logs but not the sources. Weird. Here are the sources and outputs.

[english.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831339/english.pdf)
[english.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831340/english.tex.txt)
[english_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831341/english_x.pdf)
[english_x.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831342/english_x.tex.txt)
[french.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831343/french.pdf)
[french.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831344/french.tex.txt)
[french_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831345/french_x.pdf)
[french_x.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831346/french_x.tex.txt)
[german.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831347/german.pdf)
[german.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831348/german.tex.txt)
[german_x.pdf](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831349/german_x.pdf)
[german_x.tex.txt](https://github.com/BinetReseau/polytechnique-LaTeX/files/1831350/german_x.tex.txt)

Little advice, when having problems with pandoc, start by trying only latex and reducing your tex file to a minimal example. That said, it might just be the fact that you don't use the `\textquote` command as (I think, old memory) advised in the csquotes package.
